# Generated by Django 3.1.4 on 2020-12-28 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_onlinenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlinenumber',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
