# Generated by Django 3.1.4 on 2020-12-28 12:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_class2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Class2',
        ),
        migrations.RemoveField(
            model_name='onlinenumber',
            name='datetime',
        ),
        migrations.AddField(
            model_name='onlinenumber',
            name='addDate',
            field=models.DateField(default=datetime.datetime(2020, 12, 28, 12, 45, 1, 50935, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='onlinenumber',
            name='addTime',
            field=models.TimeField(default=datetime.datetime(2020, 12, 28, 12, 45, 1, 50935, tzinfo=utc)),
        ),
    ]
