# Generated by Django 3.1.4 on 2020-12-28 12:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_auto_20201228_2045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onlinenumber',
            name='addDate',
        ),
        migrations.RemoveField(
            model_name='onlinenumber',
            name='addTime',
        ),
        migrations.AddField(
            model_name='onlinenumber',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 12, 28, 12, 48, 29, 538604, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='onlinenumber',
            name='time',
            field=models.TimeField(default=datetime.datetime(2020, 12, 28, 12, 48, 29, 538604, tzinfo=utc)),
        ),
    ]
