# Generated by Django 3.1.4 on 2021-01-02 09:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_auto_20201228_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account',
            field=models.CharField(default='account', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='user_header',
            field=models.ImageField(default='media/headers/header.png', upload_to='media/headers/'),
        ),
        migrations.AlterField(
            model_name='onlinenumber',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='onlinenumber',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
