# Generated by Django 3.1.4 on 2021-02-28 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_auto_20210102_1703'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserB',
            fields=[
                ('user_b_id', models.AutoField(primary_key=True, serialize=False)),
                ('mid', models.CharField(max_length=20)),
            ],
        ),
    ]
