# Generated by Django 3.1.4 on 2021-02-28 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_userb'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserB',
            new_name='UsersOfB',
        ),
    ]
