# Generated by Django 3.1.4 on 2021-03-01 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_auto_20210228_1345'),
    ]

    operations = [
        migrations.CreateModel(
            name='proxies',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('iport', models.CharField(max_length=20)),
            ],
        ),
    ]
