# Generated by Django 3.1.4 on 2021-03-01 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_auto_20210301_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersofb',
            name='mid',
            field=models.CharField(default='None', max_length=20, unique=True),
        ),
    ]
