# Generated by Django 3.1.4 on 2021-03-10 11:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideosDate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mid', models.CharField(default='None', max_length=20, unique=True)),
                ('dateTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('view', models.IntegerField()),
                ('coin', models.IntegerField()),
                ('danmaku', models.IntegerField()),
                ('reply', models.IntegerField()),
                ('share', models.IntegerField()),
                ('like', models.IntegerField()),
                ('favorite', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='OnlineNumber',
        ),
    ]
