# Generated by Django 3.1.4 on 2021-03-10 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_auto_20210310_1922'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VideosDate',
            new_name='VideosData',
        ),
    ]
