# Generated by Django 3.1.4 on 2021-03-10 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_auto_20210310_1938'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videosdata',
            old_name='mid',
            new_name='bvid',
        ),
    ]
