# Generated by Django 3.1.4 on 2021-03-10 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_auto_20210310_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videosdata',
            name='coin',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='videosdata',
            name='danmaku',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='videosdata',
            name='favorite',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='videosdata',
            name='like',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='videosdata',
            name='reply',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='videosdata',
            name='share',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='videosdata',
            name='view',
            field=models.IntegerField(default=0),
        ),
    ]
