# Generated by Django 3.1.4 on 2021-03-10 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_auto_20210310_2004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videosdata',
            old_name='like',
            new_name='love',
        ),
    ]
