# Generated by Django 3.1.4 on 2021-03-10 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_auto_20210310_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videosdata',
            name='bvid',
            field=models.CharField(default='None', max_length=20),
        ),
    ]
