# Generated by Django 3.1.4 on 2021-03-11 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0022_auto_20210310_2046'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTimeInfo',
            fields=[
                ('user_time_info_id', models.AutoField(primary_key=True, serialize=False)),
                ('mid', models.CharField(default='None', max_length=20)),
                ('fans', models.IntegerField(default=0)),
                ('archive_view', models.IntegerField(default=0)),
                ('archive_like', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='usersofb',
            name='digital_count',
            field=models.IntegerField(default=0, max_length=30),
        ),
        migrations.AddField(
            model_name='usersofb',
            name='food_count',
            field=models.IntegerField(default=0, max_length=30),
        ),
        migrations.AddField(
            model_name='usersofb',
            name='game_count',
            field=models.IntegerField(default=0, max_length=30),
        ),
        migrations.AddField(
            model_name='usersofb',
            name='info_count',
            field=models.IntegerField(default=0, max_length=30),
        ),
        migrations.AddField(
            model_name='usersofb',
            name='knowlege_count',
            field=models.IntegerField(default=0, max_length=30),
        ),
        migrations.AddField(
            model_name='usersofb',
            name='live_count',
            field=models.IntegerField(default=0, max_length=30),
        ),
        migrations.AddField(
            model_name='usersofb',
            name='movie_count',
            field=models.IntegerField(default=0, max_length=30),
        ),
    ]
