# Generated by Django 3.1.4 on 2021-03-11 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0025_usersofb_video_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersofb',
            name='fans_month_ago',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usersofb',
            name='fans_week_ago',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usersofb',
            name='fans_yesterday',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usersofb',
            name='fansd_month_ago',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usersofb',
            name='fansd_week_ago',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usersofb',
            name='fansd_yesterday',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usersofb',
            name='video_count_week_ago',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usersofb',
            name='videod_week_ago',
            field=models.IntegerField(default=0),
        ),
    ]
