# Generated by Django 3.1.4 on 2021-03-11 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0026_auto_20210311_2206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersofb',
            name='digital_count',
        ),
        migrations.RemoveField(
            model_name='usersofb',
            name='food_count',
        ),
        migrations.RemoveField(
            model_name='usersofb',
            name='game_count',
        ),
        migrations.RemoveField(
            model_name='usersofb',
            name='info_count',
        ),
        migrations.RemoveField(
            model_name='usersofb',
            name='knowlege_count',
        ),
        migrations.RemoveField(
            model_name='usersofb',
            name='live_count',
        ),
        migrations.RemoveField(
            model_name='usersofb',
            name='movie_count',
        ),
        migrations.AddField(
            model_name='usersofb',
            name='video_count_month_ago',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usersofb',
            name='videod_month_ago',
            field=models.IntegerField(default=0),
        ),
    ]
