# Generated by Django 3.1.4 on 2021-03-13 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0027_auto_20210312_0146'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebComment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bvid', models.CharField(default='None', max_length=20)),
                ('user_account', models.CharField(default='None', max_length=20)),
                ('web_likes', models.IntegerField(default=0)),
                ('web_replys', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='WebReply',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reply_id', models.CharField(default='None', max_length=20)),
                ('reply_content', models.CharField(default='None', max_length=100)),
                ('user_account', models.CharField(default='None', max_length=20)),
                ('reply_like', models.IntegerField(default=0)),
                ('reply_unlike', models.IntegerField(default=0)),
            ],
        ),
    ]
