# Generated by Django 3.1.4 on 2021-03-13 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0028_webcomment_webreply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='webcomment',
            old_name='bvid',
            new_name='comment_id',
        ),
        migrations.AddField(
            model_name='webreply',
            name='comment_id',
            field=models.CharField(default='None', max_length=20),
        ),
    ]
