# Generated by Django 3.1.4 on 2021-03-13 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0031_auto_20210313_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='webcomment',
            name='is_like',
            field=models.BooleanField(default=0),
        ),
    ]
