# Generated by Django 3.1.4 on 2021-03-13 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0032_webcomment_is_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webreply',
            name='reply_id',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
