# Generated by Django 3.1.4 on 2021-03-13 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0035_webreply_is_dislike'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLikeReply',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reply_id', models.CharField(default='None', max_length=50)),
                ('user_account', models.CharField(default='None', max_length=20)),
                ('is_like', models.BooleanField(default=0)),
                ('is_dislike', models.BooleanField(default=0)),
            ],
        ),
    ]
