# Generated by Django 3.1.4 on 2021-03-13 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0036_userlikereply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webreply',
            name='is_dislike',
        ),
        migrations.RemoveField(
            model_name='webreply',
            name='is_like',
        ),
    ]
