# Generated by Django 3.1.4 on 2021-03-16 11:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0038_auto_20210316_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='webcomment',
            name='like_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
