# Generated by Django 3.1.4 on 2021-03-21 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0041_userfans'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfans',
            name='name',
        ),
        migrations.AlterField(
            model_name='userfans',
            name='mid',
            field=models.CharField(default='None', max_length=20),
        ),
    ]
